# Pre-commit hooks for cat-window-watcher
# Install: pip install pre-commit
# Setup: pre-commit install
# Run manually: pre-commit run --all-files

repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version should match or be compatible with dev-requirements.txt (>=0.6.0)
    rev: v0.8.4
    hooks:
      # Run the linter
      - id: ruff
        args: [--fix]
        types_or: [python, pyi]
      # Run the formatter
      - id: ruff-format
        types_or: [python, pyi]
